name: medica
description: hospital management system

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any
  dio: ^5.3.3
  bloc: ^8.0.1
  flutter_bloc: ^8.1.3
  form_builder_validators: ^9.0.0
  flutter_form_builder: ^9.0.0
  pinput: ^4.0.0
#  material_color_utilities: ^0.8.0
  flutter_svg: ^2.0.10+1
  animations: ^2.0.11
  #  storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0

  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.2
  jwt_decoder: ^2.0.1
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  injectable: ^2.3.2
  get_it: ^7.6.7
  gap: ^3.0.1
  flutter_screenutil: ^5.9.0
  go_router: ^13.2.0
  permission_handler: ^11.3.1

  zego_uikit_prebuilt_call: ^4.12.0
  zego_uikit_signaling_plugin: ^2.7.13
  zego_uikit: ^2.23.0
  zego_zimkit: ^1.18.7
  zego_zpns: ^2.2.0

  firebase_messaging: ^15.0.2
  firebase_core: ^3.1.1

dependency_overrides:
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  #  analyzer: ^6.4.1

  icons_launcher: ^2.1.4
  flutter_native_splash: ^2.3.5

  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  retrofit_generator: '>=7.0.0 <8.0.0'
  json_serializable: ^6.7.1
  freezed: ^2.4.7




  test: ^1.24.3

flutter:


  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/
    - assets/fonts/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  android_12:
    color: "#ffffff"
    image: assets/images/splash12.png
    icon_background_color_dark: "#121212"
    image_dark: assets/images/splash12dark.png
    color_dark: "#121212"

  color: "#ffffff"
  color_dark: "#121212"

  android: true
  ios: true
  web: false
  image: assets/images/splash.png
  image_dark: assets/images/splash-dark.png

