// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1ZwVDWZUcApPdzzsuhhvTJKvcwTBOpI4',
    appId: '1:107199559924:web:0a252fe89a923823b446a1',
    messagingSenderId: '107199559924',
    projectId: 'hospital-1b047',
    authDomain: 'hospital-1b047.firebaseapp.com',
    storageBucket: 'hospital-1b047.appspot.com',
    measurementId: 'G-R1HKWHHQ6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY1WMG3pGTCMW0TF37D192efijvtkyHCY',
    appId: '1:107199559924:android:cf6f03f18f52feeeb446a1',
    messagingSenderId: '107199559924',
    projectId: 'hospital-1b047',
    storageBucket: 'hospital-1b047.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARTO6uOhyBn0PyQPl3AMyxGas-gcbzvi4',
    appId: '1:107199559924:ios:0dcd529f29ded286b446a1',
    messagingSenderId: '107199559924',
    projectId: 'hospital-1b047',
    storageBucket: 'hospital-1b047.appspot.com',
    iosBundleId: 'com.example.medica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1ZwVDWZUcApPdzzsuhhvTJKvcwTBOpI4',
    appId: '1:107199559924:web:41168733e1e66c9fb446a1',
    messagingSenderId: '107199559924',
    projectId: 'hospital-1b047',
    authDomain: 'hospital-1b047.firebaseapp.com',
    storageBucket: 'hospital-1b047.appspot.com',
    measurementId: 'G-DLSC84KSJ2',
  );
}
